---
apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    jenkins: "agent"
    job: "helmfile"
spec:
  containers:
    - args:
        - "99d"
      command:
        - "sleep"
      env:
        - name: "HOME"
          value: "/home/helm"
      image: "jenkinsciinfra/helmfile:025921"
      imagePullPolicy: "IfNotPresent"
      name: "helmfile"
      securityContext:
        privileged: false
      tty: true
    - args:
        - "99d"
      command:
        - "sleep"
      env:
        - name: "HOME"
          value: "/home/helm"
      image: "cytopia/yamllint:1.22"
      imagePullPolicy: "Always"
      name: "yamllint"
      securityContext:
        privileged: false
      tty: true
    - args:
        - "99d"
      command:
        - "sleep"
      image: "garethjevans/jcasc-validator:0.0.3"
      imagePullPolicy: "Always"
      name: "jcasc-validator"
      securityContext:
        privileged: false
      tty: true
  restartPolicy: "Never"
