---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: github-access-token
spec:
  backendType: gcpSecretsManager
  projectId: {{ .Values.github.token.project }}
  data:
    - key: {{ .Chart.Name }}-token
      name: password
      version: latest
  template:
    metadata:
      annotations:
        "jenkins.io/credentials-description": "github access token"
      labels:
        "jenkins.io/credentials-type": "usernamePassword"
    data:
      username: {{ .Values.github.token.username | b64enc | quote }}
