---
github:
  user: "Gareth Evans"
  email: "gareth@bryncynfelin.co.uk"
  username: "garethjevans"
  token: "UPDATECLI_GITHUB_TOKEN"
  branch: "main"
  owner: "garethjevans"
  repository: "ci.jenkins.io"
