---
helmDefaults:
  atomic: true
  force: false
  timeout: 600
  wait: true

repositories:
  - name: kubernetes-external-secrets
    url: https://external-secrets.github.io/kubernetes-external-secrets
releases:
  - name: kubernetes-external-secrets
    chart: kubernetes-external-secrets/kubernetes-external-secrets
    version: 6.1.0
    namespace: jenkins
    values:
      - "../config/default/kubernetes-external-secrets.yaml"
    set:
      - name: namespace
        value: jenkins
