---
helmDefaults:
  atomic: true
  force: false
  timeout: 300
  wait: true

releases:
  - name: external-secrets
    chart: external-secrets/external-secrets
    version: 0.6.1
    namespace: external-secrets
    values:
      - "../config/default/external-secrets.yaml"
    set:
      - name: namespace
        value: external-secrets
