---
helmDefaults:
  atomic: true
  force: false
  timeout: 600
  wait: true

releases:
  - name: kubernetes-external-secrets
    chart: kubernetes-external-secrets/kubernetes-external-secrets
    version: 6.4.0
    namespace: jenkins
    values:
      - "../config/default/kubernetes-external-secrets.yaml"
    set:
      - name: namespace
        value: jenkins
