---
helmDefaults:
  atomic: false
  force: false
  timeout: 600
  wait: true

releases:
  - name: captain-hook
    chart: captain-hook/captain-hook
    version: 0.0.15
    namespace: jenkins
    values:
      - "../config/default/captain-hook.yaml"
    set:
      - name: namespace
        value: jenkins
