---
helmDefaults:
  atomic: true
  force: false
  timeout: 600
  wait: true

repositories:
  - name: jenkins
    url: https://charts.jenkins.io
releases:
  - name: jenkins
    chart: jenkins/jenkins
    version: 3.0.11
    namespace: jenkins
    values:
      - "../config/default/ci-infra-io.yaml"
      #    secrets:
      #      - "../secrets/config/jenkins-infra/jenkins.yaml"
    set:
      - name: namespace
        value: jenkins
