---
helmDefaults:
  atomic: false
  force: false
  timeout: 600
  wait: true

releases:
  - name: jenkins
    chart: jenkins/jenkins
    version: 3.1.9
    namespace: jenkins
    values:
      - "../config/default/ci-infra-io.yaml"
    set:
      - name: namespace
        value: jenkins
