name: Update Charts

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: "5 * * * *"

permissions:
  contents: "write"
  pull-requests: "write"

jobs:

  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install UpdateCLI
      uses: updatecli/updatecli-action@v2

    - name: Run UpdateCLI
      id: updatecli
      run: |
        output=$(updatecli apply --push=false --config .updatecli/helm-charts --values .updatecli/values.github-action.yaml)
        echo $output
        output="${output//$'\n'/\\n}"
        
        echo "stdout=$output" >> $GITHUB_OUTPUT

    - name: Display Body
      run: |
        echo ${{ steps.updatecli.outputs.stdout }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      if: github.event_name != 'pull_request'
      with:
        commit-message: 'chore: bumped chart versions'
        signoff: false
        title: 'chore: bumped chart versions'
        body: ${{ steps.updatecli.outputs.stdout }} 
