---
name: Update Jenkins Version

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  update_cli:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install UpdateCLI
        uses: updatecli/updatecli-action@v2

      - name: Update CLI
        run: |
          updatecli apply --debug --push=false --config .updatecli/jenkins --values .updatecli/values.github-action.yaml
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          commit-message: 'chore(deps): update jenkins version'
          committer: Gareth Evans <gareth@bryncynfelin.co.uk>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          title: 'chore(deps): update jenkins version'
