name: Update Charts

on:
  workflow_dispatch:
  schedule:
    - cron: "5 * * * *"

permissions:
  contents: "write"
  pull-requests: "write"

jobs:

  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install UpdateCLI
      uses: updatecli/updatecli-action@v2

    - name: Run UpdateCLI
      id: updatecli
      run: |
        updatecli apply --push=false --config .updatecli/helm-charts --values .updatecli/values.github-action.yaml
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      if: github.event_name != 'pull_request'
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        commit-message: 'chore: bumped chart versions'
        signoff: false
        branch: update-charts
        title: 'chore: bumped chart versions'
        body: ${{ steps.updatecli.outputs.stdout }} 
