---
name: Update CLI

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  update_cli:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Update CLI
        uses: docker://olblak/updatecli:v0.0.31
        with:
          entrypoint: updatecli
          args: apply --push=false --config ./updateCli/updatecli.d --values ./updateCli/values.github-action.yaml

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          commit-message: 'chore(deps): update jenkins version'
          committer: Gareth Evans <gareth@bryncynfelin.co.uk>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          title: 'chore(deps): update jenkins version'
