---
name: Update CLI

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  update_cli:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Update CLI
        run: |
          curl -sSfL -o updatecli.tar.gz https://github.com/updatecli/updatecli/releases/latest/download/updatecli_Linux_x86_64.tar.gz
          tar xvfz updatecli.tar.gz
          rm updatecli.tar.gz
          rm LICENSE
          rm README.adoc
          chmod +x ./updatecli
          ./updatecli version
          ./updatecli apply --debug --push=false --config ./updateCli/updatecli.d --values ./updateCli/values.github-action.yaml
          rm updatecli
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          commit-message: 'chore(deps): update jenkins version'
          committer: Gareth Evans <gareth@bryncynfelin.co.uk>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          title: 'chore(deps): update jenkins version'
